
INSTALL_DIR="/opt/"

REDIS_VERSION=6.0.3
SPARK_VERSION=3.3.0
MEMTIER_VERSION=2.1.4

REDIS_DIR=${INSTALL_DIR}/redis-${REDIS_VERSION}/
SPARK_DIR=${INSTALL_DIR}/spark-${SPARK_VERSION}-bin-hadoop3/
MEMTIER_DIR=${INSTALL_DIR}/memtier_benchmark-${MEMTIER_VERSION}
